// decklink_prores_capture.cpp
// Multi-device DeckLink capture → CUDA ProRes encode → .mov benchmark.
//
// Purpose: stress-test how many simultaneous 1080i50 V210 DeckLink inputs
//          the machine can sustain before dropping frames.  Each device gets
//          its own pinned ring buffer, CUDA stream, encoder context, and .mov
//          output file written in parallel.  Stats are printed every 10 s so
//          you can watch exactly when and on which card drops start.
//
// Usage:
//   decklink_prores_capture [options]
//
//   --devices  "Dev A,Dev B"  Comma-separated device names (partial match OK)
//   --count    N              Use the first N enumerated DeckLink cards
//              (default when neither is specified: all available cards)
//   --profile  <proxy|lt|std|hq|0-3>      default: hq
//   --duration <seconds>                   default: 240
//   --outdir   <directory>                 default: current directory
//
// Each device writes to: <outdir>/capture_<card>_<profile>.mov
//
// Companion CPU run for comparison (DeckLink card not used by this program):
//   ffmpeg -f decklink -i "DeckLink 1" -t 240 -c:v prores_ks -profile:v hq \
//          -y out_cpu_hq.mov
//
// Requirements on target PC:
//   - DeckLink Desktop Video driver installed (provides the COM servers)
//   - CUDA-capable GPU (any sm_5.2+ device)
//   - No MSVC or CUDA DLLs required  (CRT and cudart are statically linked)
// ---------------------------------------------------------------------------
#define NOMINMAX
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <comdef.h>
#include <objbase.h>

// DeckLink COM interfaces — generated by MIDL from SDK .idl files.
// DeckLinkAPI_i.c (compiled alongside this .cpp) provides all IID/CLSID GUIDs.
#include "../../../modules/decklink/interop/DecklinkAPI.h"

#include <cuda_runtime.h>
#include "../cuda/cuda_prores_frame.h"
#include "../cuda/cuda_prores_tables.cuh"
#include "../muxer/mov_muxer.h"
#include "../timecode.h"

#include <atomic>
#include <chrono>
#include <condition_variable>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

// ─── Constants ───────────────────────────────────────────────────────────────
static constexpr int kWidth      = 1920;
static constexpr int kHeight     = 1080;
static constexpr int kV210Stride = (kWidth / 6) * 16;          // 5 120 B/row
static constexpr int kFrameBytes = kV210Stride * kHeight;       // 5 529 600 B
static constexpr int kRingN      = 8;                           // ring slots per device
static constexpr int kMaxDevices = 8;

static const char *kProfileNames[] = { "proxy", "lt",  "std",  "hq"  };
static const char *kProfileLong[]  = { "Proxy", "LT",  "Std",  "HQ"  };
static const uint32_t kFourccs[]   = {
    0x6170636F, // 'apco' Proxy
    0x6170636C, // 'apcl' LT
    0x6170636E, // 'apcn' Standard
    0x61706368, // 'apch' HQ
};

// ─── CUDA helper ─────────────────────────────────────────────────────────────
static void cuda_check(cudaError_t e, const char *tag)
{
    if (e != cudaSuccess) {
        fprintf(stderr, "CUDA error [%s]: %s\n", tag, cudaGetErrorString(e));
        exit(1);
    }
}

// ─── Per-device state ────────────────────────────────────────────────────────
struct DeviceCtx {
    // Identity
    int         idx           = 0;    // 1-based enum index
    std::string name;
    std::string output_path;
    int         profile       = 3;

    // DeckLink COM objects
    IDeckLinkInput *input     = nullptr;

    // Pinned ring buffer
    uint8_t *ring_buf[kRingN] = {};
    std::atomic<int64_t> write_count{0};  // incremented by capture callback
    std::atomic<int64_t> read_count{0};   // incremented by encoder thread
    std::atomic<int64_t> dropped{0};
    std::atomic<int64_t> first_drop_write{-1}; // write_count at first drop (-1 = none)
    std::mutex           ring_mtx;
    std::condition_variable ring_cv;

    // CUDA encoder
    ProResFrameCtx enc    = {};
    uint32_t      *d_v210 = nullptr;
    cudaStream_t   stream = nullptr;

    // Muxer (initialised in main, closed in encoder thread)
    MovMuxer mux;

    // Metrics (written only by encoder thread; read by stats thread)
    std::atomic<int64_t>  frames_encoded{0};
    std::atomic<uint64_t> bytes_out{0};

    // Timing baseline (set once before capture starts)
    std::chrono::steady_clock::time_point t_start;
};

// ─── Encoder context helpers ─────────────────────────────────────────────────
static void enc_ctx_create(ProResFrameCtx &ctx, int profile, int mbs_per_slice = 8)
{
    ctx = {};
    ctx.width          = kWidth;
    ctx.height         = kHeight;
    ctx.profile        = profile;
    ctx.q_scale        = 8;
    ctx.is_interlaced  = true; // 1080i50 = top-field-first

    int mb_cols = kWidth  / 16;
    int mb_rows = kHeight / 16;
    ctx.mbs_per_slice    = mbs_per_slice;
    ctx.slices_per_row   = mb_cols / mbs_per_slice;
    ctx.num_slices       = ctx.slices_per_row * mb_rows;
    ctx.blocks_per_slice = 8 * mbs_per_slice;

    int y_px = kWidth * kHeight;
    int c_px = (kWidth / 2) * kHeight;
    cuda_check(cudaMalloc(&ctx.d_y,  y_px * sizeof(int16_t)), "d_y");
    cuda_check(cudaMalloc(&ctx.d_cb, c_px * sizeof(int16_t)), "d_cb");
    cuda_check(cudaMalloc(&ctx.d_cr, c_px * sizeof(int16_t)), "d_cr");
    cuda_check(cudaMalloc(&ctx.d_coeffs_y,  y_px * sizeof(int16_t)), "d_coeffs_y");
    cuda_check(cudaMalloc(&ctx.d_coeffs_cb, c_px * sizeof(int16_t)), "d_coeffs_cb");
    cuda_check(cudaMalloc(&ctx.d_coeffs_cr, c_px * sizeof(int16_t)), "d_coeffs_cr");

    size_t se = (size_t)ctx.num_slices * ctx.blocks_per_slice * 64;
    cuda_check(cudaMalloc(&ctx.d_coeffs_slice, se * sizeof(int16_t)), "d_coeffs_slice");
    size_t bs = se * sizeof(int16_t) * 2 + (size_t)ctx.num_slices * 32;
    cuda_check(cudaMalloc(&ctx.d_bitstream,     bs),                                          "d_bitstream");
    cuda_check(cudaMalloc(&ctx.d_slice_offsets, (size_t)(ctx.num_slices + 1) * sizeof(uint32_t)), "d_offsets");
    cuda_check(cudaMalloc(&ctx.d_slice_sizes,   (size_t) ctx.num_slices       * sizeof(uint32_t)), "d_sizes");
    cuda_check(cudaMalloc(&ctx.d_bit_counts,    (size_t) ctx.num_slices * 3   * sizeof(uint32_t)), "d_bits");
    ctx.cub_temp_bytes = 8 * 1024 * 1024;
    cuda_check(cudaMalloc(&ctx.d_cub_temp, ctx.cub_temp_bytes), "d_cub");
    ctx.h_frame_buf_size = (size_t)kWidth * kHeight * 4;
    cuda_check(cudaMallocHost(&ctx.h_frame_buf, ctx.h_frame_buf_size), "h_frame");
}

static void enc_ctx_destroy(ProResFrameCtx &ctx)
{
    cudaFree(ctx.d_y);       cudaFree(ctx.d_cb);        cudaFree(ctx.d_cr);
    cudaFree(ctx.d_coeffs_y); cudaFree(ctx.d_coeffs_cb); cudaFree(ctx.d_coeffs_cr);
    cudaFree(ctx.d_coeffs_slice);
    cudaFree(ctx.d_bitstream); cudaFree(ctx.d_slice_offsets);
    cudaFree(ctx.d_slice_sizes); cudaFree(ctx.d_bit_counts);
    cudaFree(ctx.d_cub_temp);
    cudaFreeHost(ctx.h_frame_buf);
    memset(&ctx, 0, sizeof(ctx));
}

// ─── DeckLink capture callback ───────────────────────────────────────────────
class CaptureCallback : public IDeckLinkInputCallback
{
public:
    explicit CaptureCallback(DeviceCtx &d) : dev_(d) {}

    HRESULT STDMETHODCALLTYPE VideoInputFormatChanged(
        BMDVideoInputFormatChangedEvents, IDeckLinkDisplayMode *,
        BMDDetectedVideoInputFormatFlags) override { return S_OK; }

    HRESULT STDMETHODCALLTYPE VideoInputFrameArrived(
        IDeckLinkVideoInputFrame    *videoFrame,
        IDeckLinkAudioInputPacket * /*audio*/) override
    {
        if (!videoFrame) return S_OK;

        int64_t w = dev_.write_count.load(std::memory_order_relaxed);
        int64_t r = dev_.read_count.load(std::memory_order_acquire);
        if (w - r >= kRingN) {
            // Ring is full — the GPU encoder is lagging
            int64_t expected = -1;
            dev_.first_drop_write.compare_exchange_strong(
                expected, w, std::memory_order_relaxed);
            dev_.dropped.fetch_add(1, std::memory_order_relaxed);
            return S_OK;
        }

        int    slot = (int)(w % kRingN);
        void  *src  = nullptr;
        videoFrame->GetBytes(&src);
        long   rows = videoFrame->GetHeight();
        long   rb   = videoFrame->GetRowBytes();
        size_t cb   = (size_t)rb * (size_t)rows;
        if (cb > kFrameBytes) cb = kFrameBytes;
        memcpy(dev_.ring_buf[slot], src, cb);

        dev_.write_count.fetch_add(1, std::memory_order_release);
        dev_.ring_cv.notify_one();
        return S_OK;
    }

    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID, LPVOID *) override { return E_NOINTERFACE; }
    ULONG   STDMETHODCALLTYPE AddRef()  override { return ++m_ref; }
    ULONG   STDMETHODCALLTYPE Release() override
    {
        ULONG v = --m_ref;
        if (!v) delete this;
        return v;
    }

private:
    DeviceCtx          &dev_;
    std::atomic<ULONG>  m_ref{1};
};

// ─── Encoder thread (one per device) ─────────────────────────────────────────
static void encoder_thread_func(DeviceCtx *dev,
                                 std::atomic<bool> *stop_flag,
                                 const ProResColorDesc *color)
{
    int64_t processed = 0;

    while (true) {
        // Wait for a frame or stop signal
        {
            std::unique_lock<std::mutex> lk(dev->ring_mtx);
            dev->ring_cv.wait_for(lk, std::chrono::milliseconds(50), [&] {
                return dev->write_count.load(std::memory_order_acquire) > processed;
            });
        }

        // Drain every available slot before rechecking stop
        int64_t avail = dev->write_count.load(std::memory_order_acquire);
        while (processed < avail) {
            int slot = (int)(processed % kRingN);

            cuda_check(cudaMemcpyAsync(
                dev->d_v210, dev->ring_buf[slot], kFrameBytes,
                cudaMemcpyHostToDevice, dev->stream), "H2D");

            size_t out_size = 0;
            cudaError_t e = prores_encode_frame(
                &dev->enc, dev->d_v210,
                dev->enc.h_frame_buf, &out_size,
                dev->stream, color);
            if (e != cudaSuccess) {
                fprintf(stderr, "[Dev #%d] encode error: %s\n",
                        dev->idx, cudaGetErrorString(e));
                stop_flag->store(true);
                goto done;
            }

            dev->mux.write_video(dev->enc.h_frame_buf, out_size,
                                  (uint64_t)processed);
            dev->bytes_out.fetch_add(out_size, std::memory_order_relaxed);
            processed++;
            dev->frames_encoded.fetch_add(1, std::memory_order_relaxed);
            dev->read_count.store(processed, std::memory_order_release);
        }

        if (stop_flag->load() &&
            dev->write_count.load(std::memory_order_acquire) <= processed)
            break;
    }

done:
    cudaStreamSynchronize(dev->stream);
    dev->mux.close();
}

// ─── Command-line parsing ─────────────────────────────────────────────────────
struct Args {
    std::vector<std::string> devices;  // parsed from --devices
    int  count    = 0;    // from --count  (0 = all)
    int  profile  = 3;    // 0-3
    int  duration = 240;  // seconds
    std::string outdir;   // output directory
};

static void print_usage(const char *exe)
{
    fprintf(stderr,
        "Usage: %s [options]\n"
        "\n"
        "  --devices  \"Name1,Name2\"  Comma-separated DeckLink device names (partial match)\n"
        "  --count    N              Use first N enumerated DeckLink devices\n"
        "             (default: all available cards)\n"
        "  --profile  proxy|lt|std|hq|0-3    default: hq\n"
        "  --duration <seconds>               default: 240\n"
        "  --outdir   <directory>             default: current directory\n"
        "\n"
        "Each device captures simultaneously.  Stats are printed every 10 s.\n"
        "First frame-drop on each card is highlighted so you can find the hardware limit.\n",
        exe);
}

static std::vector<std::string> split_csv(const std::string &s)
{
    std::vector<std::string> out;
    size_t start = 0;
    while (start < s.size()) {
        size_t p = s.find(',', start);
        if (p == std::string::npos) p = s.size();
        std::string tok = s.substr(start, p - start);
        // trim whitespace
        size_t a = tok.find_first_not_of(" \t");
        size_t b = tok.find_last_not_of(" \t");
        if (a != std::string::npos) out.push_back(tok.substr(a, b - a + 1));
        start = p + 1;
    }
    return out;
}

static Args parse_args(int argc, char *argv[])
{
    Args a;
    for (int i = 1; i < argc; i++) {
        if      (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) { print_usage(argv[0]); exit(0); }
        else if (strcmp(argv[i], "--devices")  == 0 && i+1 < argc) a.devices  = split_csv(argv[++i]);
        else if (strcmp(argv[i], "--count")    == 0 && i+1 < argc) a.count    = atoi(argv[++i]);
        else if (strcmp(argv[i], "--duration") == 0 && i+1 < argc) a.duration = atoi(argv[++i]);
        else if (strcmp(argv[i], "--outdir")   == 0 && i+1 < argc) a.outdir   = argv[++i];
        else if (strcmp(argv[i], "--profile")  == 0 && i+1 < argc) {
            const char *p = argv[++i];
            if      (!strcmp(p,"proxy")||!strcmp(p,"0")) a.profile = 0;
            else if (!strcmp(p,"lt")   ||!strcmp(p,"1")) a.profile = 1;
            else if (!strcmp(p,"std")  ||!strcmp(p,"2")) a.profile = 2;
            else if (!strcmp(p,"hq")   ||!strcmp(p,"3")) a.profile = 3;
            else { fprintf(stderr,"Unknown profile: %s\n",p); exit(1); }
        }
        else { fprintf(stderr,"Unknown option: %s\n", argv[i]); print_usage(argv[0]); exit(1); }
    }
    return a;
}

// ─── DeckLink enumeration ─────────────────────────────────────────────────────
// Returns the display name and releases the IDeckLink after returning the input.
struct DLEnumEntry { std::string name; IDeckLinkInput *input; };

static std::vector<DLEnumEntry> enumerate_inputs()
{
    IDeckLinkIterator *it = nullptr;
    if (FAILED(CoCreateInstance(CLSID_CDeckLinkIterator, nullptr, CLSCTX_ALL,
                                 IID_IDeckLinkIterator, (void **)&it)) || !it) {
        fprintf(stderr, "Cannot create DeckLink iterator — drivers installed?\n");
        return {};
    }
    std::vector<DLEnumEntry> result;
    IDeckLink *dl = nullptr;
    while (it->Next(&dl) == S_OK) {
        BSTR bname = nullptr;
        dl->GetDisplayName(&bname);
        std::wstring wn;
        if (bname) { wn = bname; SysFreeString(bname); }
        std::string name(wn.begin(), wn.end());

        IDeckLinkInput *inp = nullptr;
        if (SUCCEEDED(dl->QueryInterface(IID_IDeckLinkInput, (void **)&inp))) {
            result.push_back({ name, inp });
        }
        dl->Release();
    }
    it->Release();
    return result;
}

// Safe numeric-width label for a device name
static std::string safe_label(const std::string &name, int idx)
{
    // Replace spaces and special chars with underscores, cap at 24 chars
    std::string s;
    for (char c : name) {
        if (isalnum((unsigned char)c) || c == '-') s += c;
        else if (!s.empty() && s.back() != '_') s += '_';
    }
    while (!s.empty() && s.back() == '_') s.pop_back();
    if (s.empty()) s = "dev";
    if (s.size() > 24) s.resize(24);
    char buf[8];
    snprintf(buf, sizeof(buf), "d%d_", idx);
    return std::string(buf) + s;
}

// Print a stats row for one device
static void print_device_row(const DeviceCtx &dev, double elapsed,
                              double interval_secs, int64_t prev_encoded)
{
    int64_t cur     = dev.frames_encoded.load(std::memory_order_relaxed);
    int64_t dropped = dev.dropped.load(std::memory_order_relaxed);
    uint64_t bytes  = dev.bytes_out.load(std::memory_order_relaxed);

    double fps   = (interval_secs > 0) ? (double)(cur - prev_encoded) / interval_secs : 0.0;
    double mbps  = (elapsed > 0)       ? (bytes * 8.0 / 1e6) / elapsed                : 0.0;

    int64_t fdrop = dev.first_drop_write.load(std::memory_order_relaxed);
    char drop_note[64] = "";
    if (dropped > 0 && fdrop >= 0) {
        // Approximate: first drop was at frame ~fdrop / 25 fps
        double drop_t = (double)fdrop / 25.0;
        snprintf(drop_note, sizeof(drop_note), "  ← first drop at t≈%.1f s", drop_t);
    }

    fprintf(stdout, "  #%-2d  %-28s  %6lld fr  %5.1f fps  %6.1f Mbps  drop=%lld%s\n",
            dev.idx, dev.name.c_str(),
            (long long)cur, fps, mbps, (long long)dropped,
            drop_note);
}

// ─── main ─────────────────────────────────────────────────────────────────────
int main(int argc, char *argv[])
{
    Args args = parse_args(argc, argv);

    // ── COM + CUDA init ───────────────────────────────────────────────────────
    CoInitialize(nullptr);

    int n_cuda = 0;
    cuda_check(cudaGetDeviceCount(&n_cuda), "GetDeviceCount");
    if (!n_cuda) { fprintf(stderr, "No CUDA devices found.\n"); return 1; }
    {
        cudaDeviceProp p{};
        cudaGetDeviceProperties(&p, 0);
        fprintf(stdout, "[CUDA]    %s  (sm_%d%d,  %.0f MB)\n",
                p.name, p.major, p.minor, p.totalGlobalMem / 1048576.0);
    }

    // ── Upload quantisation tables to GPU ─────────────────────────────────────
    prores_tables_upload();

    // ── Enumerate DeckLink devices ────────────────────────────────────────────
    auto all_inputs = enumerate_inputs();
    if (all_inputs.empty()) {
        fprintf(stderr, "No DeckLink input devices found.\n");
        return 1;
    }

    // Select subset based on --devices or --count
    std::vector<DLEnumEntry *> selected;
    if (!args.devices.empty()) {
        for (auto &spec : args.devices) {
            bool is_idx = !spec.empty();
            for (char c : spec) if (!isdigit((unsigned char)c)) { is_idx = false; break; }
            int idx_target = is_idx ? atoi(spec.c_str()) : -1;

            bool found = false;
            for (int k = 0; k < (int)all_inputs.size(); k++) {
                bool match = (idx_target > 0)
                    ? (k + 1 == idx_target)
                    : (all_inputs[k].name.find(spec) != std::string::npos);
                if (match) { selected.push_back(&all_inputs[k]); found = true; break; }
            }
            if (!found) fprintf(stderr, "  Warning: device '%s' not found — skipping\n", spec.c_str());
        }
    } else {
        int limit = (args.count > 0) ? args.count : kMaxDevices;
        for (int k = 0; k < (int)all_inputs.size() && k < limit; k++)
            selected.push_back(&all_inputs[k]);
    }

    if (selected.empty()) { fprintf(stderr, "No matching DeckLink devices.\n"); return 1; }
    if ((int)selected.size() > kMaxDevices) selected.resize(kMaxDevices);

    int n_dev = (int)selected.size();
    fprintf(stdout, "[DeckLink] %d device(s) selected  |  Profile: %s  |  Duration: %d s\n",
            n_dev, kProfileLong[args.profile], args.duration);

    // ── Build per-device contexts ─────────────────────────────────────────────
    std::vector<std::unique_ptr<DeviceCtx>>  devs;
    std::vector<CaptureCallback *>           callbacks;

    for (int i = 0; i < n_dev; i++) {
        auto d = std::make_unique<DeviceCtx>();
        d->idx     = i + 1;
        d->name    = selected[i]->name;
        d->input   = selected[i]->input;
        d->profile = args.profile;

        // Output path
        std::string label = safe_label(d->name, d->idx);
        d->output_path = (args.outdir.empty() ? "." : args.outdir)
                         + "\\" + label + "_" + kProfileNames[args.profile] + ".mov";

        // Pinned ring buffers
        for (int r = 0; r < kRingN; r++)
            cuda_check(cudaMallocHost(&d->ring_buf[r], kFrameBytes), "ring");

        // CUDA stream + encoder context
        cuda_check(cudaStreamCreate(&d->stream), "streamCreate");
        enc_ctx_create(d->enc, args.profile);
        cuda_check(cudaMalloc(&d->d_v210, kFrameBytes), "d_v210");

        // MOV muxer
        std::wstring wout(d->output_path.begin(), d->output_path.end());
        MovVideoTrackInfo vi{};
        vi.width = kWidth; vi.height = kHeight;
        vi.timebase_num  = 1;  vi.timebase_den = 25;
        vi.prores_fourcc = kFourccs[args.profile];
        vi.color.color_primaries = 1; vi.color.transfer_function = 1;
        vi.color.color_matrix    = 1; vi.color.has_hdr            = false;
        MovAudioTrackInfo ai{};  // no audio — muxer omits audio track
        if (!d->mux.open(wout, vi, ai)) {
            fprintf(stderr, "Cannot create output file: %s\n", d->output_path.c_str());
            return 1;
        }

        fprintf(stdout, "  #%-2d  %-36s  →  %s\n",
                d->idx, d->name.c_str(), d->output_path.c_str());

        // DeckLink: enable + callback
        if (FAILED(d->input->EnableVideoInput(
                bmdModeHD1080i50, bmdFormat10BitYUV, bmdVideoInputFlagDefault))) {
            fprintf(stderr, "  #%d EnableVideoInput failed — 1080i50 signal present?\n", d->idx);
            return 1;
        }
        auto *cb = new CaptureCallback(*d);
        d->input->SetCallback(cb);
        callbacks.push_back(cb);
        devs.push_back(std::move(d));
    }

    // ── Start all streams ─────────────────────────────────────────────────────
    fprintf(stdout, "\nStarting capture on %d device(s) ...\n", n_dev);
    fflush(stdout);

    auto t_start = std::chrono::steady_clock::now();
    for (auto &d : devs) d->t_start = t_start;

    for (auto &d : devs) {
        if (FAILED(d->input->StartStreams())) {
            fprintf(stderr, "StartStreams failed on #%d\n", d->idx);
        }
    }

    // ── Encoder threads ───────────────────────────────────────────────────────
    std::atomic<bool> stop_flag{false};
    const ProResColorDesc color = COLOR_DESC_SDR_709;

    std::vector<std::thread> enc_threads;
    for (auto &d : devs)
        enc_threads.emplace_back(encoder_thread_func, d.get(), &stop_flag, &color);

    // ── Stats loop (main thread) ──────────────────────────────────────────────
    // Track per-device frames at the last report for delta-fps
    std::vector<int64_t> prev_encoded(n_dev, 0);
    auto t_last_report = t_start;

    fprintf(stdout, "\n");
    fprintf(stdout, "  #   %-28s  %8s  %9s  %10s  %s\n",
            "Device", "Frames", "FPS", "Mbps", "Dropped");
    fprintf(stdout, "  %s\n", std::string(80, '-').c_str());

    while (true) {
        std::this_thread::sleep_for(std::chrono::seconds(1));

        auto   now     = std::chrono::steady_clock::now();
        double elapsed = std::chrono::duration<double>(now - t_start).count();
        double since   = std::chrono::duration<double>(now - t_last_report).count();

        if (since >= 10.0) {
            fprintf(stdout, "\n  [ t = %6.1f s ]\n", elapsed);
            for (int i = 0; i < n_dev; i++) {
                print_device_row(*devs[i], elapsed, since, prev_encoded[i]);
                prev_encoded[i] = devs[i]->frames_encoded.load(std::memory_order_relaxed);
            }
            fflush(stdout);
            t_last_report = now;
        }

        if (elapsed >= args.duration) break;
    }

    // ── Stop capture ──────────────────────────────────────────────────────────
    fprintf(stdout, "\nStopping capture ...\n");
    for (auto &d : devs) d->input->StopStreams();
    stop_flag.store(true);
    for (auto &d : devs) d->ring_cv.notify_all();

    for (auto &t : enc_threads) t.join();

    // ── Final summary ─────────────────────────────────────────────────────────
    double total = std::chrono::duration<double>(
        std::chrono::steady_clock::now() - t_start).count();

    fprintf(stdout, "\n");
    fprintf(stdout, "=================================================================\n");
    fprintf(stdout, "  CAPTURE SUMMARY   profile=%s   duration=%.1f s\n",
            kProfileLong[args.profile], total);
    fprintf(stdout, "=================================================================\n");
    fprintf(stdout, "  #   %-30s  %7s  %7s  %7s  %7s  %s\n",
            "Device", "Frames", "AvgFPS", "AvgMbps", "Dropped", "First drop");
    fprintf(stdout, "  %s\n", std::string(80, '-').c_str());

    bool any_drop = false;
    for (auto &d : devs) {
        int64_t  enc     = d->frames_encoded.load(std::memory_order_relaxed);
        int64_t  dropped = d->dropped.load(std::memory_order_relaxed);
        uint64_t bytes   = d->bytes_out.load(std::memory_order_relaxed);
        double   fps     = (total > 0) ? enc / total : 0.0;
        double   mbps    = (total > 0) ? (bytes * 8.0 / 1e6) / total : 0.0;
        int64_t  fdrop   = d->first_drop_write.load(std::memory_order_relaxed);

        char drop_t[32] = "–";
        if (fdrop >= 0) { snprintf(drop_t, sizeof(drop_t), "%.1f s", (double)fdrop / 25.0); any_drop = true; }

        fprintf(stdout, "  #%-2d %-30s  %7lld  %7.1f  %7.1f  %7lld  %s\n",
                d->idx, d->name.c_str(),
                (long long)enc, fps, mbps, (long long)dropped, drop_t);
    }

    if (!any_drop)
        fprintf(stdout, "\n  All %d devices completed with zero dropped frames.\n", n_dev);
    else
        fprintf(stdout, "\n  Drops detected — see 'First drop' column for per-device onset.\n");

    fprintf(stdout, "\nOutput files:\n");
    for (auto &d : devs)
        fprintf(stdout, "  %s\n", d->output_path.c_str());

    fprintf(stdout,
        "\nCPU reference (run simultaneously on a spare card):\n"
        "  ffmpeg -f decklink -i \"<device>\" -t %d -c:v prores_ks -profile:v %s"
        " -y out_cpu_%s.mov\n",
        args.duration, kProfileNames[args.profile], kProfileNames[args.profile]);
    fflush(stdout);

    // ── Cleanup ───────────────────────────────────────────────────────────────
    for (int i = 0; i < n_dev; i++) {
        devs[i]->input->DisableVideoInput();
        devs[i]->input->SetCallback(nullptr);
        callbacks[i]->Release();
        devs[i]->input->Release();
        cudaStreamDestroy(devs[i]->stream);
        cudaFree(devs[i]->d_v210);
        enc_ctx_destroy(devs[i]->enc);
        for (int r = 0; r < kRingN; r++) cudaFreeHost(devs[i]->ring_buf[r]);
    }
    // Release any non-selected input interfaces
    for (auto &e : all_inputs) e.input->Release();

    CoUninitialize();
    return 0;
}

